#!/bin/bash
set -e
export CI=true
bundle exec rake spec:unit

echo
echo "Using sqlite3:"
bundle exec rake spec:integrated

echo
echo "Using postgres:"
bundle exec rake spec:integrated DB=postgres

echo
echo "Using mysql:"
bundle exec rake spec:integrated DB=mysql
